version: "3"

services:
  db:
    image: mysql:5
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: helloworld

    volumes:
      - ~/docker/data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db

  maildev:
    image: djfarrelly/maildev
    ports:
      - 8081:80

  app:
    build: .
    ports:
      - 9074:80
    volumes:
      - ./vhosts:/etc/apache2/sites-enabled
      - ./www:/var/www
