version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker image"
          command: |
            docker login -u ${DOCKER_LOGIN} -p ${DOCKER_HUB_PASSWORD}
            docker build -t guillaumehanotel/cd_app
            docker push guillaumehanotel/cd_app

workflows:
  version: 2
  build:
    jobs:
      - build